meta_product_name: Qui a beté?”
meta_title: Qui a beté? - Les paris entre potes”
meta_description: “Les paris entre potes ne seront plus jamais oubliés. Crée ton crew, et lances tes bets."
meta_image: logoqabweb.png” # should exist in `app/assets/images/`
twitter_account: “@product_twitter_account”   # required for Twitter Cards